name: Test

on:
  pull_request:
    branches:
      - development
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
      with:
        node-version: '12.x'
        registry-url: 'https://npm.pkg.github.com'
    - name: Install dependencies
      run: npm ci
    - name: Build
      run: npm run build
    - name: Lint
      run: npm run lint
    - name: Test
      run: log_silent=true npm test
